### PR TITLE
Add extmarks inserter

### PR DESCRIPTION
**Pull request by gpanders**

### CODE REVIEW

**Comment by ranjithshegde** [comment]
Hey. Thank you for this PR. I am trying it out.

Can you please confirm that `lua return require('snippets').expand_or_advance(1)` and such things work? I am not having success. I have tried both "suggested mappings" approach and personal mappings

**Comment by gpanders** [comment]
They should work. At least they are working just fine for me.

**Comment by ranjithshegde** [comment]
Strange. They just wont move from first placeholder to next, no matter what mappings I follow. When I press the right key, it just flickers once and then nothing
I am only texting on lsp-snippets so far

**Comment by gpanders** [comment]
I am just using user-defined text snippets, so perhaps that has something to do with it.

**Comment by gpanders** [comment]
I'm going to close this as I don't think this implementation is really production ready.

**Pull request closed without merging**
